version: "3.1"

services:
  # This is kept in sync with docker-compose.api.yml, except for
  # CHALICE_LOCAL_USE_PROD_ENV.
  braintrust-redis:
    image: public.ecr.aws/braintrust/redis:latest
    ports:
      - 6479:6379
    extra_hosts:
      - "host.docker.internal:host-gateway"
  braintrust-postgres:
    image: public.ecr.aws/braintrust/postgres:latest
    command: postgres -c config_file=/etc/postgresql.conf
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - 5532:5432
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - api_pg_volume:/var/lib/postgresql/data
  braintrust-standalone-api:
    image: public.ecr.aws/braintrust/standalone-api:latest
    env_file:
      - .env
    environment:
      DEFAULT_HOSTNAME: host.docker.internal
    ports:
      - 8000:8000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      braintrust-redis:
        condition: service_healthy
      braintrust-postgres:
        condition: service_healthy

  braintrust-standalone-app:
    image: public.ecr.aws/braintrust/standalone-app:latest
    env_file:
      - .env
    ports:
      - 3000:3000
    extra_hosts:
      - "host.docker.internal:host-gateway"
  braintrust-standalone-app-bootstrap:
    image: public.ecr.aws/braintrust/standalone-app-bootstrap:latest
    env_file:
      - .env
    ports:
      - 8100:8100
    extra_hosts:
      - "host.docker.internal:host-gateway"
  braintrust-standalone-proxy:
    image: public.ecr.aws/braintrust/standalone-proxy:latest
    environment:
      BRAINTRUST_APP_URL: http://host.docker.internal:3000
    ports:
      - 8787:8787
    extra_hosts:
      - "host.docker.internal:host-gateway"
  braintrust-standalone-realtime:
    image: public.ecr.aws/braintrust/standalone-realtime:latest
    ports:
      - 8788:8788
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  api_pg_volume: null
