# Each docker container can be configured with environment variables. Many of
# these variables point the container to the other services, which may be other
# containers you have deployed or centrally-hosted Braintrust services.
#
# - REDIS_URL: Connection URI for the redis instance for internal container use.
# The general form of the URI is
# `redis://[user[:password]@][host][:port][/db-number][?param1=value1&param2=value2...]`.
# Defaults to the URI for the `braintrust-redis` docker service.
#
# - PG_URL: Connection URI for the postgres instance for internal container use.
# The general form of the URI is
# `postgresql://[user[:password]@][host][:port][/dbname][?param1=value1&param2=value2...]`.
# Defaults to the URI for the 'braintrust-postgres' docker service. See
# https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-CONNSTRING-URIS
# for full details on the URI spec.
#
# - CLICKHOUSE_PG_URL: Connection URI for the clickhouse instance over the
# postgres wire protocol, for internal container use. Takes the same URI form as
# PG_URL. Defaults to the postgres URI for the 'braintrust-clickhouse' docker
# service on port 9005.
#
# - CLICKHOUSE_CONNECT_URL: Connection URI for the clickhouse instance over the
# clickhouse-connect protocol, for internal container use. The general form of
# the URI is
# `clickhouse:[//[user[:password]@][hosts_and_ports]][/database][?query_parameters]`.
# Defaults to the HTTP URI for the 'braintrust-clickhouse' docker service on
# port 8123. See
# https://clickhouse.com/docs/en/integrations/sql-clients/cli#connection_string
# for full details on the URI spec.
#
# Note: if you want to run the API with clickhouse (currently it defaults to
# off), simply uncomment the relevant blocks of configuration code. Each
# relevant block is preceeded by a comment starting with "To disable
# clickhouse".

version: "3.1"

services:
  braintrust-redis:
    image: public.ecr.aws/braintrust/redis:latest
    ports:
      - 6479:6379
    extra_hosts:
      - "host.docker.internal:host-gateway"
  braintrust-postgres:
    image: public.ecr.aws/braintrust/postgres:latest
    command: postgres -c config_file=/etc/postgresql.conf
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - 5532:5432
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - api_pg_volume:/var/lib/postgresql/data
  # To disable clickhouse, comment out this entire service definition.
  #braintrust-clickhouse:
  #  image: public.ecr.aws/braintrust/clickhouse:latest
  #  environment:
  #    CLICKHOUSE_USER: default
  #    CLICKHOUSE_PASSWORD: default
  #  ports:
  #    # Port for connecting through HTTP.
  #    - 8123:8123
  #    # Port for connecting through postgres.
  #    - 9005:9005
  #    # Port for connecting through the clickhouse client binary. This is not
  #    # used by Braintrust but can be useful for poking around the clickhouse
  #    # instance yourself.
  #    - 9000:9000
  #    # See https://clickhouse.com/docs/en/guides/sre/network-ports for a full
  #    # list of ports used by clickhouse.
  #  extra_hosts:
  #    - "host.docker.internal:host-gateway"
  #  volumes:
  #    - api_clickhouse_volume:/var/lib/clickhouse
  #    - api_clickhouse_logs_volume:/var/log/clickhouse-server
  #    # In order to configure clickhouse to store data in Amazon S3, you can use
  #    # the template configuration file at
  #    # https://github.com/braintrustdata/braintrust-deployment/blob/main/docker/clickhouse/storage_config.xml
  #    # and mount it into the clickhouse container. You will need to configure
  #    # your S3 URL in 'storage_config.xml' and include any relevant auth
  #    # credentials in the clickhouse container. See
  #    # https://clickhouse.com/docs/en/integrations/s3#managing-credentials for
  #    # full details.
  #    # - ./clickhouse/storage_config.xml:/etc/clickhouse-server/config.d/storage_config.xml
  braintrust-standalone-api:
    image: public.ecr.aws/braintrust/standalone-api:latest
    environment:
      # This variable instructs the API to connect to the centrally-hosted
      # components.
      CHALICE_LOCAL_USE_PROD_ENV: 1
      PG_URL: postgres://postgres:postgres@host.docker.internal:5532/postgres
      #CLICKHOUSE_PG_URL: postgres://default:default@host.docker.internal:9005/default
      #CLICKHOUSE_CONNECT_URL: clickhouse://default:default@host.docker.internal:8123/default
      # To disable clickhouse, replace the CLICKHOUSE_PG_URL and
      # CLICKHOUSE_CONNECT_URL settings with the ones below, which explicitly
      # set them to an empty string.
      CLICKHOUSE_PG_URL: ""
      CLICKHOUSE_CONNECT_URL: ""
      REDIS_URL: redis://host.docker.internal:6479/0
      # If you are deploying any other services yourself, such as the proxy or
      # realtime, you may override their URLs here as well (PROXY_URL and
      # REALTIME_URL, respectively). See the environment settings in
      # docker-compose.full.yml for a starting point.
    ports:
      - 8000:8000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      # To disable clickhouse, comment out this dependency on
      # `braintrust-clickhouse`.
      #braintrust-clickhouse:
      #  condition: service_healthy
      braintrust-redis:
        condition: service_healthy
      braintrust-postgres:
        condition: service_healthy

volumes:
  api_pg_volume: null
  # To disable clickhouse, comment out these volume definitions.
  #api_clickhouse_volume: null
  #api_clickhouse_logs_volume: null
